version: "3"

services:
        urlshortener_nginx:
             depends_on:
                    - urlshortener_php
             image: nginx:alpine
             container_name: urlshortener_nginx
             volumes:
                 - ./code/public/api:/var/www/backend
                 - ./nginx/conf.d:/etc/nginx/conf.d

             ports:
                 - 8080:80
                 - 443:443 
             networks:
                 - app-network
        
        urlshortener_php: 
             depends_on:
                    - urlshortener_mariadb
             container_name: urlshortener_php
             volumes:
                     - ./code/public/api:/var/www/backend
             working_dir: /var/www/backend
             build:
                    context: ./docker
                    dockerfile: Dockerfile
                    args:
                         - HOST_USER=${HOST_USER}
                         - HOST_USER_GROUP=${HOST_USER_GROUP}
                         - ENV=${ENV}
             networks:
                     - app-network


        urlshortener_mariadb:
             image: mariadb
             environment:
                 MYSQL_ROOT_PASSWORD: 1q2w3e4r
             volumes:
                 - ./data:/var/lib/mysql
             ports:
                 - "9906:3306"
             networks:
                     - app-network

        urlshortener_phpmyadmin:
           depends_on:
               - urlshortener_mariadb
           image: phpmyadmin/phpmyadmin
           restart: always
           ports:
             - 8082:80
           environment:
             PMA_HOST: urlshortener_mariadb
             MYSQL_ROOT_PASSWORD: 1q2w3e4r
           networks:
                     - app-network
               
networks:
  app-network:
    driver: bridge
